### ISSUE TITLE
Document the installation

### ISSUE THREAD

**Issue by vibhavagarwal5** [dibyadas/imagery#11]
Create a installation document stating all the necessary steps to setup the project along with the details.

**Comment by sourabh1031** [comment]
@vibhavagarwal5 i would like to work on the issue but i am not quite clear what is expected from me

**Comment by vibhavagarwal5** [comment]
@sourabh1031 That would be great. You just have to make a new file say `Installation.md` with proper installation steps. You can check the Imagery slack channel for the instructions. Just add those and maybe with some Screenshots for visual aid. This is fairly easy task with no prior knowledge. Would be great if you could finish it. 😄

**Comment by dibyadas** [comment]
Hey @sourabh1031! Thanks for your interest. Unfortunately, I forgot to reply here, this has already been done and completed by @hari-govind. I have since forgotten to close this issue. Here is the link to the docs :- https://github.com/dibyadas/imagery/wiki/Deploying-Imagery-On-Heroku

**Comment by vibhavagarwal5** [comment]
@dibyadas Atleast he can update the Readme about this maybe?

**Comment by dibyadas** [comment]
There are couple of other issues that you can try to work on if you are interested. You may try setting up the environment first and and have a look at the issues. We'll be happy to help.

**Comment by dibyadas** [comment]
Yeah, fine. That will be a quick PR. Just link the docs to the README page. :)
